### ISSUE TITLE
an Importerror

### ISSUE THREAD

**Issue by fsted** [RookieHong/python-objectness#1]
Hi,your code is great,but When i run demo.py,find an error:  
File ".\python-objectness-master\c_segment\c_segment.py", line 1, in <module>
    from c_segment import segment_img
ImportError: cannot import name 'segment_img' from 'c_segment'
how can I do it，Thanks :)

**Comment by RookieHong** [comment]
Did you follow Step.4 in [Get Started](https://github.com/RookieHong/python-objectness#get-started) to build the python interface?

**Comment by fsted** [comment]
> Did you follow Step.4 in [Get Started](https://github.com/RookieHong/python-objectness#get-started) to build the python interface?

thank you for the reply , but it says:
ModuleNotFoundError: No module named 'c_segment.build.c_segment' (ㄒoㄒ)

**Comment by RookieHong** [comment]
You need to build the python interface first:
```$ sudo apt install cmake   # Install cmake
$ cd c_segment
$ mkdir build
$ cd build
$ cmake .. && make
```

Then the module 'c_segment.build.c_segment' will exist.

**Comment by fsted** [comment]
> You need to build the python interface first:
> 
> ```
> $ cd c_segment
> $ mkdir build
> $ cd build
> $ cmake .. && make
> ```
> 
> Then the module 'c_segment.build.c_segment' will exist.

Thank you very much ，I solve it  👍

**Comment by RookieHong** [comment]
You're welcome.
